# This flow chart describes the procedure of making Apple Sandwiches.
print("Enter the work place")
print("Take apple from fridge")
print("Take Mayo from fridge")
print("Take butter from fridge")
print("Take a clean Knife")
print("Take a chopping board")
print("Chopped Apples in small pieces on chopping board")
print("Take a clean spoon")
print("Take a medium size bowl")
print("Add chopped apple in bowl using spoon")
print("Add Mayo in chopped apple using spoon")
print("Reuse spoon to add butter in Chopped Apple Mixture")
print("Add black paper into chopped apple mixture")
print("Mix the apple with other ingrediants properly")
print("Take Bread packet out from fridge")
print("Take a clean knife")
print("Spread butter on one side of bread slice")
print("Take another slice of bread")
print("Use same knife to spread butter on another slice of bread")
print("Spread apple filling on bread using spoon")
print("Place another slide of bread on top of it")
print("Turn on the grill , keep it for 10 mins to warm")
print("Put sandwich in grill")
print("Wait for 2 mins")
print("Turn off the grill")
print("Take sandwich out from the grill using spetula")
print("Serve in plate")
